"""add approved form screenshot hash

Revision ID: 0434c36501f5
Revises: 8a5e227f3d27
Create Date: 2026-09-30 00:08:03.634188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0434c36501f5'
down_revision: Union[str, Sequence[str], None] = '8a5e227f3d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('approved_form_screenshot_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'approved_form_screenshot_hash')
    # ### end Alembic commands ###
