"""add cover letter pdf path

Revision ID: 1e67ef9026e7
Revises: f229cce4b9c5
Create Date: 2026-09-29 22:13:13.865442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e67ef9026e7'
down_revision: Union[str, Sequence[str], None] = 'f229cce4b9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cover_letter_pdf_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cover_letter_pdf_path')
    # ### end Alembic commands ###
