"""add application package approval

Revision ID: 4561104bd6c5
Revises: 1e67ef9026e7
Create Date: 2026-09-29 22:24:53.840759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4561104bd6c5'
down_revision: Union[str, Sequence[str], None] = '1e67ef9026e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "applications",
        sa.Column(
            "package_approved",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "applications",
        sa.Column(
            "package_approved_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        "applications",
        sa.Column(
            "approved_cv_hash",
            sa.String(length=64),
            nullable=True,
        ),
    )

    op.add_column(
        "applications",
        sa.Column(
            "approved_cover_letter_hash",
            sa.String(length=64),
            nullable=True,
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'approved_cover_letter_hash')
    op.drop_column('applications', 'approved_cv_hash')
    op.drop_column('applications', 'package_approved_at')
    op.drop_column('applications', 'package_approved')
    # ### end Alembic commands ###
