"""add pdf path to applications

Revision ID: 56a8084a0e75
Revises: 68cc9222dee8
Create Date: 2026-09-25 15:33:41.142978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a8084a0e75'
down_revision: Union[str, Sequence[str], None] = '68cc9222dee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('pdf_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'pdf_path')
    # ### end Alembic commands ###
