"""add cover letter validation data

Revision ID: 6b0f6411a2fd
Revises: 0506b6ae7a4b
Create Date: 2026-09-29 21:47:11.732713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b0f6411a2fd'
down_revision: Union[str, Sequence[str], None] = '0506b6ae7a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cover_letter_validation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cover_letter_validation_data')
    # ### end Alembic commands ###
