"""add submission approval

Revision ID: 8a5e227f3d27
Revises: 0e9e26f65e6d
Create Date: 2026-09-29 23:59:11.706877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5e227f3d27'
down_revision: Union[str, Sequence[str], None] = '0e9e26f65e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('submission_approved', sa.Boolean(), nullable=False, server_default=sa.false()),)
    op.add_column('applications', sa.Column('submission_approved_at', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('approved_submission_hash', sa.String(length=64), nullable=True))
    op.add_column('applications', sa.Column('approved_submission_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'approved_submission_url')
    op.drop_column('applications', 'approved_submission_hash')
    op.drop_column('applications', 'submission_approved_at')
    op.drop_column('applications', 'submission_approved')
    # ### end Alembic commands ###
