"""add cover letter correction data

Revision ID: f229cce4b9c5
Revises: 6b0f6411a2fd
Create Date: 2026-09-29 21:59:43.852845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f229cce4b9c5'
down_revision: Union[str, Sequence[str], None] = '6b0f6411a2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cover_letter_correction_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cover_letter_correction_data')
    # ### end Alembic commands ###
